FROM ruby:2.7

ARG USER_ID
ARG GROUP_ID

RUN groupadd -o -g $GROUP_ID -r user
RUN useradd -u $USER_ID -g $GROUP_ID user

ENV INSTALL_APP /opt/app
RUN mkdir -p $INSTALL_APP
RUN gem update --system
RUN gem install rails bundler
RUN chown -R user:user /opt/app

WORKDIR /opt/app
USER $USER_ID

CMD ["bin/sh"]
