version: '3.7'

services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - '5432:5432'
    volumes:
      - user-postgress:/var/lib/postgressql/data

  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
    volumes:
      - user-redis:/var/lib/redis/data

  rails_demo:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "8010:8010"
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./rails_demo
        target: /opt/app/rails_demo
    env_file:
      - .env

  sidekiq:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./rails_demo
        target: /opt/app/rails_demo
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - rails_demo
    ports:
      - "8020:8020"

volumes:
  user-redis:
  user-postgress:
